apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner-2
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner-2
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs2
            - name: NFS_SERVER
              value: odroid-01.local
            - name: NFS_PATH
              value: /media/ssd/nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: odroid-01.local
            path: /media/ssd/nfs
